import { computeAvailableSlots } from "./slots.js";
import { resolveBusyTimes } from "./busy.js";
import type {
  AvailabilityStore,
  BookingNotifier,
  BookingRecord,
  BookingStore,
  BookingWidgetStore,
  CalendarSyncPort,
} from "./booking-types.js";
import type { FieldValidationIssue } from "./types.js";
import type { RateLimiter } from "./rate-limit.js";

export interface BookingDeps {
  widgets: BookingWidgetStore;
  availability: AvailabilityStore;
  bookings: BookingStore;
  calendarSync: CalendarSyncPort;
  notifier: BookingNotifier;
  rateLimiter: RateLimiter;
}

const EMAIL_PATTERN = /^[^\s@]+@[^\s@]+\.[^\s@]+$/;
const MAX_NOTES_LENGTH = 2000;

export interface CreateBookingInput {
  id: string;
  widgetId: string;
  startsAtMs: number;
  visitorName: string;
  visitorEmail: string;
  visitorTimezone: string;
  notes?: string;
  /** Pre-generated by the caller (mirrors submitForm's `id`) — the raw, one-time secret the visitor's cancel/reschedule link carries. */
  manageToken: string;
  manageBaseUrl: string;
  ownerEmail: string | null;
  now?: number;
}

export type CreateBookingOutcome =
  | { status: "created"; booking: BookingRecord; calendarSyncOk: boolean }
  | { status: "widget_not_found" }
  | { status: "rule_not_found" }
  | { status: "invalid"; issues: FieldValidationIssue[] }
  | { status: "slot_taken" }
  | { status: "rate_limited"; retryAfterMs: number };

function validateVisitorInput(input: CreateBookingInput): FieldValidationIssue[] {
  const issues: FieldValidationIssue[] = [];
  if (!input.visitorName.trim()) issues.push({ field: "visitorName", message: "Name is required" });
  if (!EMAIL_PATTERN.test(input.visitorEmail.trim())) issues.push({ field: "visitorEmail", message: "A valid email address is required" });
  if (!input.visitorTimezone.trim()) issues.push({ field: "visitorTimezone", message: "Timezone is required" });
  if ((input.notes?.length ?? 0) > MAX_NOTES_LENGTH) issues.push({ field: "notes", message: "Notes are too long" });
  if (!Number.isFinite(input.startsAtMs)) issues.push({ field: "startsAt", message: "A valid start time is required" });
  return issues;
}

/**
 * The runtime API's booking-create mutation (ADR-0007/ADR-0009). Order
 * mirrors submitForm exactly: rate-limit gates the request, then the
 * candidate slot is re-validated server-side against the rule and current
 * busy time (never trust a client-computed slot list), then the write
 * itself goes through — where the database's own unique index is the final
 * arbiter of a same-slot race (SLICES.md: "one succeeds, one is rejected
 * cleanly"), never this pre-check. Calendar push and notification are
 * best-effort afterward, exactly like notifyBestEffort/webhookBestEffort —
 * a calendar or email failure can never turn a stored booking back into a
 * failure.
 */
export async function createBooking(input: CreateBookingInput, deps: BookingDeps): Promise<CreateBookingOutcome> {
  const widget = await deps.widgets.getWidget(input.widgetId);
  if (!widget) return { status: "widget_not_found" };

  const siteLimit = deps.rateLimiter.consume(`site:${widget.siteId}`);
  if (!siteLimit.allowed) return { status: "rate_limited", retryAfterMs: siteLimit.retryAfterMs ?? 0 };

  const rule = await deps.availability.getRule(widget.siteId);
  if (!rule) return { status: "rule_not_found" };

  const issues = validateVisitorInput(input);
  if (issues.length > 0) return { status: "invalid", issues };

  const endsAtMs = input.startsAtMs + rule.slotDurationMinutes * 60_000;
  const now = input.now ?? Date.now();

  const { busy, calendarSyncOk } = await resolveBusyTimes(deps, widget.siteId, input.startsAtMs, endsAtMs);
  const offered = computeAvailableSlots({ rule, rangeStartMs: input.startsAtMs, rangeEndMs: endsAtMs, busy, now });
  const stillOffered = offered.some((s) => s.startMs === input.startsAtMs && s.endMs === endsAtMs);
  if (!stillOffered) return { status: "slot_taken" };

  const created = await deps.bookings.create({
    id: input.id,
    siteId: widget.siteId,
    widgetId: widget.id,
    startsAtMs: input.startsAtMs,
    endsAtMs,
    visitorName: input.visitorName.trim(),
    visitorEmail: input.visitorEmail.trim(),
    visitorTimezone: input.visitorTimezone,
    notes: input.notes?.trim() || null,
    manageToken: input.manageToken,
  });
  if (created.status === "slot_taken") return { status: "slot_taken" };

  await pushCalendarBestEffort(deps, widget.siteId, created.booking);
  await notifyBestEffort(deps, widget.siteId, rule.timezone, input.ownerEmail, created.booking, input.manageBaseUrl, "confirmed");

  return { status: "created", booking: created.booking, calendarSyncOk };
}

async function pushCalendarBestEffort(deps: BookingDeps, siteId: string, booking: BookingRecord): Promise<void> {
  try {
    const pushed = await deps.calendarSync.pushEvent(siteId, booking);
    if (pushed) await deps.bookings.setExternalEventId(siteId, booking.id, pushed.externalEventId);
  } catch {
    // Best-effort (SLICES.md): a calendar push failure never fails the booking itself.
  }
}

async function notifyBestEffort(
  deps: BookingDeps,
  siteId: string,
  ownerTimezone: string,
  ownerEmail: string | null,
  booking: BookingRecord,
  manageBaseUrl: string,
  kind: "confirmed" | "canceled" | "rescheduled",
): Promise<void> {
  try {
    if (kind === "confirmed") await deps.notifier.notifyConfirmed({ siteId, booking, ownerEmail, ownerTimezone, manageBaseUrl });
    else if (kind === "canceled") await deps.notifier.notifyCanceled({ siteId, booking, ownerEmail, ownerTimezone });
    else await deps.notifier.notifyRescheduled({ siteId, booking, ownerEmail, ownerTimezone, manageBaseUrl });
  } catch {
    // Best-effort, same as forms' notifyBestEffort — the write already succeeded.
  }
}

export type CancelBookingOutcome = { status: "canceled"; booking: BookingRecord } | { status: "not_found" };

/** Visitor-initiated cancel, resolved by manage token — siteId is already known (the link's own URL carries it), so this is a `bookings_tenant_isolation`-scoped lookup with no principal at all. */
export async function cancelBookingByToken(
  input: { siteId: string; bookingId: string; manageToken: string; ownerEmail: string | null; ownerTimezone: string },
  deps: Pick<BookingDeps, "bookings" | "calendarSync" | "notifier">,
): Promise<CancelBookingOutcome> {
  const booking = await deps.bookings.getByManageToken(input.siteId, input.bookingId, input.manageToken);
  if (!booking) return { status: "not_found" };
  return finishCancel(input.siteId, input.bookingId, input.ownerEmail, input.ownerTimezone, deps);
}

/** Owner-initiated cancel, authenticated (site membership already checked by the caller) — same finish path as the visitor's own link. */
export async function cancelBookingAsOwner(
  input: { siteId: string; bookingId: string; ownerEmail: string | null; ownerTimezone: string },
  deps: Pick<BookingDeps, "bookings" | "calendarSync" | "notifier">,
): Promise<CancelBookingOutcome> {
  return finishCancel(input.siteId, input.bookingId, input.ownerEmail, input.ownerTimezone, deps);
}

async function finishCancel(
  siteId: string,
  bookingId: string,
  ownerEmail: string | null,
  ownerTimezone: string,
  deps: Pick<BookingDeps, "bookings" | "calendarSync" | "notifier">,
): Promise<CancelBookingOutcome> {
  const canceled = await deps.bookings.cancel(siteId, bookingId);
  if (!canceled) return { status: "not_found" };

  try {
    await deps.calendarSync.cancelEvent(siteId, canceled);
  } catch {
    // Best-effort — the cancellation itself already succeeded and released the slot.
  }
  try {
    await deps.notifier.notifyCanceled({ siteId, booking: canceled, ownerEmail, ownerTimezone });
  } catch {
    // Best-effort, same discipline as every other notify path here.
  }

  return { status: "canceled", booking: canceled };
}

export type RescheduleBookingOutcome =
  | { status: "rescheduled"; booking: BookingRecord; calendarSyncOk: boolean }
  | { status: "not_found" }
  | { status: "slot_taken" }
  | { status: "invalid"; issues: FieldValidationIssue[] };

/** Visitor-initiated reschedule, resolved by manage token — re-validates the new slot exactly like createBooking does, excluding the booking's own current interval from "busy" so moving within a widow of nearby availability isn't blocked by itself. */
export async function rescheduleBookingByToken(
  input: { siteId: string; bookingId: string; manageToken: string; newStartsAtMs: number; ownerEmail: string | null; ownerTimezone: string; manageBaseUrl: string; now?: number },
  deps: BookingDeps,
): Promise<RescheduleBookingOutcome> {
  const booking = await deps.bookings.getByManageToken(input.siteId, input.bookingId, input.manageToken);
  if (!booking) return { status: "not_found" };
  if (!Number.isFinite(input.newStartsAtMs)) return { status: "invalid", issues: [{ field: "startsAt", message: "A valid start time is required" }] };

  const rule = await deps.availability.getRule(input.siteId);
  if (!rule) return { status: "not_found" };
  const widget = await deps.widgets.getWidget(booking.widgetId);
  if (!widget) return { status: "not_found" };

  const newEndsAtMs = input.newStartsAtMs + rule.slotDurationMinutes * 60_000;
  const now = input.now ?? Date.now();

  const { busy: rawBusy, calendarSyncOk } = await resolveBusyTimes(deps, input.siteId, input.newStartsAtMs, newEndsAtMs);
  const busy = rawBusy.filter((b) => b.sourceId !== booking.id);
  const offered = computeAvailableSlots({ rule, rangeStartMs: input.newStartsAtMs, rangeEndMs: newEndsAtMs, busy, now });
  const stillOffered = offered.some((s) => s.startMs === input.newStartsAtMs && s.endMs === newEndsAtMs);
  if (!stillOffered) return { status: "slot_taken" };

  const result = await deps.bookings.reschedule(input.siteId, input.bookingId, input.newStartsAtMs, newEndsAtMs);
  if (result.status !== "rescheduled") return result;

  try {
    await deps.calendarSync.updateEvent(input.siteId, result.booking);
  } catch {
    // Best-effort.
  }
  await notifyBestEffort(deps, input.siteId, input.ownerTimezone, input.ownerEmail, result.booking, input.manageBaseUrl, "rescheduled");

  return { status: "rescheduled", booking: result.booking, calendarSyncOk };
}
