/**
 * KAN-1137 / ADR-0005: one-off payment blocks, bring-your-own Stripe.
 * Deliberately independent of @prefab/schema, @prefab/db and every
 * control-plane package (ADR-0010 / CLAUDE.md invariant 4) — apps/self-host
 * reimplements the storage/provider interfaces below against SQLite and a
 * fake-or-real TenantStripeProvider of its own, exactly the same "narrow
 * port, injected" shape submit.ts (FormManifestStore/SubmissionStore) and
 * book.ts (BookingStore/CalendarSyncPort) already use.
 */

/** The publish-safe manifest a Payment block's props are snapshotted into — see @prefab/db's `payment_blocks` table (0009_slice10_payments.sql). */
export interface PaymentBlockManifest {
  id: string;
  siteId: string;
  heading: string;
  description: string;
  buttonLabel: string;
  /** Cents — the one field a visitor's own request must never be able to override (a tampered request could otherwise pay whatever it likes). Always resolved from this manifest, never from the runtime checkout request body. */
  amount: number;
  currency: string;
  successMessage: string;
}

export interface PaymentBlockStore {
  getBlock(blockId: string): Promise<PaymentBlockManifest | null>;
}

export type StripeConnectionStatus = "connected" | "error";

/** What the runtime needs from a site's own connected Stripe account — apps/api's real shape (with the row's id/timestamps) lives in @prefab/db's stripe-connections.ts; only this much crosses the containment boundary. */
export interface StripeConnectionRecord {
  stripeAccountId: string;
  accessToken: string;
  status: StripeConnectionStatus;
}

export interface StripeConnectionStore {
  getConnection(siteId: string): Promise<StripeConnectionRecord | null>;
}

export interface CreatedPaymentRecord {
  id: string;
}

export interface PaymentRecordStore {
  create(input: { id: string; siteId: string; blockId: string; stripeSessionId: string; amount: number; currency: string }): Promise<CreatedPaymentRecord>;
}

export interface TenantCheckoutSession {
  sessionId: string;
  url: string;
}

/**
 * The narrow port this module needs from a tenant's own Stripe — mirrors
 * apps/api/src/lib/tenant-stripe-provider.ts's `TenantStripeProvider`
 * shape exactly, but only the one method (and only the fields)
 * `createPaymentCheckout` actually calls; `connect`/`constructEvent` are
 * apps/api-only concerns (OAuth and webhook verification are both
 * control-plane operations with no reason to cross into @prefab/runtime).
 */
export interface TenantCheckoutProvider {
  createCheckoutSession(input: {
    accessToken: string;
    stripeAccountId: string;
    amount: number;
    currency: string;
    productName: string;
    successUrl: string;
    cancelUrl: string;
    paymentRecordId: string;
    siteId: string;
  }): Promise<TenantCheckoutSession>;
}

export interface CreatePaymentCheckoutDeps {
  paymentBlocks: PaymentBlockStore;
  stripeConnections: StripeConnectionStore;
  paymentRecords: PaymentRecordStore;
  tenantStripe: TenantCheckoutProvider;
}

export interface CreatePaymentCheckoutInput {
  /** Pre-generated by the caller (mirrors submitForm's/createBooking's own `id`) — also what the real Stripe adapter threads through Checkout's `client_reference_id`/`metadata` so a real webhook (which has no siteId in its own URL) can resolve tenant context before ever touching `payment_records` (R20 / RLS). */
  id: string;
  blockId: string;
  successUrl: string;
  cancelUrl: string;
}

export type CreatePaymentCheckoutOutcome =
  | { status: "created"; url: string }
  | { status: "not_found" }
  | { status: "no_connection" }
  | { status: "provider_error" };

/**
 * The runtime API's payment-checkout mutation (ADR-0007's "form submit,
 * booking create, later checkout" — this is that "later"). The block's own
 * amount/currency are looked up from the publish-safe manifest, never
 * accepted from the caller, so a tampered request can never pay a
 * different amount than the block's own author configured. Provider
 * failures (no live Stripe account reachable, a bad/rotated tenant token)
 * surface as `provider_error` rather than a stored, doomed-to-never-
 * complete payment record — unlike submitForm/createBooking, there is no
 * "the write already happened, only notification can still fail" step
 * here: creating the Checkout session IS the operation that can fail, and
 * it happens before any row is written.
 */
export async function createPaymentCheckout(input: CreatePaymentCheckoutInput, deps: CreatePaymentCheckoutDeps): Promise<CreatePaymentCheckoutOutcome> {
  const block = await deps.paymentBlocks.getBlock(input.blockId);
  if (!block) return { status: "not_found" };

  const connection = await deps.stripeConnections.getConnection(block.siteId);
  if (!connection) return { status: "no_connection" };

  let session: TenantCheckoutSession;
  try {
    session = await deps.tenantStripe.createCheckoutSession({
      accessToken: connection.accessToken,
      stripeAccountId: connection.stripeAccountId,
      amount: block.amount,
      currency: block.currency,
      productName: block.heading || "Payment",
      successUrl: input.successUrl,
      cancelUrl: input.cancelUrl,
      paymentRecordId: input.id,
      siteId: block.siteId,
    });
  } catch {
    return { status: "provider_error" };
  }

  await deps.paymentRecords.create({
    id: input.id,
    siteId: block.siteId,
    blockId: block.id,
    stripeSessionId: session.sessionId,
    amount: block.amount,
    currency: block.currency,
  });

  return { status: "created", url: session.url };
}

/**
 * KAN-1154 / ADR-0016: the recurring counterpart to
 * createPaymentCheckout above — same narrow-port-injected shape, same
 * "resolve the block's own publish-safe manifest, never trust a visitor's
 * request for anything money-shaped" discipline, but a *sibling* set of
 * types rather than new branches on the one-off ones above (ADR-0016's
 * question 1: a subscription's price is per-interval, and its lifecycle is
 * rewritten indefinitely rather than settled once — genuinely different
 * shapes, not the same shape with an extra field). `StripeConnectionStore`
 * IS reused unchanged from above: a connected Stripe account is the same
 * account regardless of whether it's charged once or on a schedule.
 */

/** The publish-safe manifest a Subscription block's props are snapshotted into — see @prefab/db's `subscription_blocks` table (0012_kan1154_subscriptions.sql). */
export interface SubscriptionBlockManifest {
  id: string;
  siteId: string;
  heading: string;
  description: string;
  buttonLabel: string;
  /** Cents, PER INTERVAL — see PaymentBlockManifest.amount's own comment; the same "never accepted from the visitor's own checkout request" discipline applies here, renamed to `price` because it isn't a one-time total (ADR-0016). */
  price: number;
  currency: string;
  interval: "month" | "year";
  trialPeriodDays: number;
  successMessage: string;
}

export interface SubscriptionBlockStore {
  getBlock(blockId: string): Promise<SubscriptionBlockManifest | null>;
}

export interface CreatedSubscriptionRecord {
  id: string;
}

export interface SubscriptionRecordStore {
  create(input: {
    id: string;
    siteId: string;
    blockId: string;
    stripeCheckoutSessionId: string;
    price: number;
    currency: string;
    interval: "month" | "year";
    trialPeriodDays: number;
  }): Promise<CreatedSubscriptionRecord>;
}

/**
 * The narrow port this module needs from a tenant's own Stripe for a
 * subscription checkout — mirrors `TenantCheckoutProvider` above, and
 * apps/api/src/lib/tenant-stripe-provider.ts's `TenantStripeProvider.
 * createSubscriptionCheckoutSession` exactly, but only the one method (and
 * only the fields) `createSubscriptionCheckout` actually calls.
 */
export interface TenantSubscriptionCheckoutProvider {
  createSubscriptionCheckoutSession(input: {
    accessToken: string;
    stripeAccountId: string;
    price: number;
    currency: string;
    interval: "month" | "year";
    trialPeriodDays: number;
    productName: string;
    successUrl: string;
    cancelUrl: string;
    subscriptionRecordId: string;
    siteId: string;
  }): Promise<TenantCheckoutSession>;
}

export interface CreateSubscriptionCheckoutDeps {
  subscriptionBlocks: SubscriptionBlockStore;
  /** Reused unchanged from the one-off payment port above — see this section's own module comment for why. */
  stripeConnections: StripeConnectionStore;
  subscriptionRecords: SubscriptionRecordStore;
  tenantStripe: TenantSubscriptionCheckoutProvider;
}

export interface CreateSubscriptionCheckoutInput {
  /** Pre-generated by the caller — same reasoning as CreatePaymentCheckoutInput.id's own comment. */
  id: string;
  blockId: string;
  successUrl: string;
  cancelUrl: string;
}

export type CreateSubscriptionCheckoutOutcome =
  | { status: "created"; url: string }
  | { status: "not_found" }
  | { status: "no_connection" }
  | { status: "provider_error" };

/**
 * The runtime API's subscription-checkout mutation (ADR-0016 part 1 —
 * creation only; see that ADR for what part 2's webhook handler still owes
 * this record once it's created). The block's own price/currency/interval/
 * trialPeriodDays are looked up from the publish-safe manifest, never
 * accepted from the caller, for the identical reason createPaymentCheckout
 * never trusts a visitor's own amount. The created `subscription_records`
 * row starts 'incomplete' (its column default) and stays there until a
 * follow-up card's webhook consumer resolves it — this function's job ends
 * once the Checkout session itself is created.
 */
export async function createSubscriptionCheckout(
  input: CreateSubscriptionCheckoutInput,
  deps: CreateSubscriptionCheckoutDeps,
): Promise<CreateSubscriptionCheckoutOutcome> {
  const block = await deps.subscriptionBlocks.getBlock(input.blockId);
  if (!block) return { status: "not_found" };

  const connection = await deps.stripeConnections.getConnection(block.siteId);
  if (!connection) return { status: "no_connection" };

  let session: TenantCheckoutSession;
  try {
    session = await deps.tenantStripe.createSubscriptionCheckoutSession({
      accessToken: connection.accessToken,
      stripeAccountId: connection.stripeAccountId,
      price: block.price,
      currency: block.currency,
      interval: block.interval,
      trialPeriodDays: block.trialPeriodDays,
      productName: block.heading || "Subscription",
      successUrl: input.successUrl,
      cancelUrl: input.cancelUrl,
      subscriptionRecordId: input.id,
      siteId: block.siteId,
    });
  } catch {
    return { status: "provider_error" };
  }

  await deps.subscriptionRecords.create({
    id: input.id,
    siteId: block.siteId,
    blockId: block.id,
    stripeCheckoutSessionId: session.sessionId,
    price: block.price,
    currency: block.currency,
    interval: block.interval,
    trialPeriodDays: block.trialPeriodDays,
  });

  return { status: "created", url: session.url };
}

/**
 * KAN-1245 / ADR-0018 cart addendum: multi-item cart checkout, a *third*
 * sibling to createPaymentCheckout/createSubscriptionCheckout above, not a
 * branch on either — a cart has no single block to resolve a manifest from
 * at all (it spans however many products a visitor added, off any one
 * page), and `mode: "payment"` only (no subscription products in a cart
 * this milestone, already settled with the user). The one thing this
 * function shares with the two above: money is ALWAYS resolved
 * server-side, never trusted from the caller — here that means re-reading
 * every `products` row fresh on every call (unlike payment_blocks/
 * subscription_blocks' immutable publish-time snapshot, `products.price`/
 * `stockCount` are live and mutable — see the ADR addendum's point 1 for
 * why a snapshot would defeat the entire purpose of this milestone's
 * "never trust the client for money" checkout).
 */

/** The one per-item shape `TenantCartCheckoutProvider` needs — deliberately narrower than `CartCheckoutLineItem` below (drops `productId`/`fulfillmentType`, which the actual Stripe line item never needs), the same "identical, separately-declared shape across this boundary" convention `CreateCheckoutSessionInput`/`CreateSubscriptionCheckoutSessionInput` already use in apps/api/src/lib/tenant-stripe-provider.ts. */
export interface CartCheckoutSessionLineItem {
  /** Cents. */
  unitAmount: number;
  currency: string;
  title: string;
  quantity: number;
}

/** Server-configured, never visitor-supplied — see the ADR addendum's point 4 for why a real per-site owner setting is deferred, and why the amount/allowed-countries here must never come from the runtime checkout request body. */
export interface CartShippingConfig {
  /** Cents — applied verbatim regardless of the cart's own resolved currency (see the ADR addendum's point 4). */
  flatRateAmount: number;
  /** Stripe's `shipping_options[0][shipping_rate_data][display_name]`. */
  label: string;
  /** ISO 3166-1 alpha-2, uppercase, e.g. ["US"]. */
  allowedCountries: string[];
}

export interface TenantCartCheckoutProvider {
  createCartCheckoutSession(input: {
    accessToken: string;
    stripeAccountId: string;
    items: CartCheckoutSessionLineItem[];
    /** Every item above already shares this one currency — see createCartCheckout's own mixed-currency rejection below. */
    currency: string;
    successUrl: string;
    cancelUrl: string;
    cartCheckoutRecordId: string;
    siteId: string;
    requiresShipping: boolean;
    shipping: CartShippingConfig;
  }): Promise<TenantCheckoutSession>;
}

/** The current, live state of one `products` row this cart references — resolved fresh on every checkout call, never from a publish-time snapshot (see this section's own module comment). */
export interface CartProductManifest {
  id: string;
  siteId: string;
  title: string;
  /** Cents — the CURRENT price, re-read at checkout time; never trusted from the visitor's own cart. */
  price: number;
  currency: string;
  fulfillmentType: "physical" | "digital_or_service";
  /** null for a digital/service product (nothing to run out of). */
  stockCount: number | null;
}

export interface CartProductStore {
  /** Only ever returns a published product — relies entirely on `products_public_read` (0014_kan1245_cart_checkout.sql), scoped to `status = 'published'`. Same contract as PaymentBlockStore.getBlock. */
  getProduct(productId: string): Promise<CartProductManifest | null>;
}

/** One resolved, server-validated cart line — built by createCartCheckout below, persisted verbatim into `cart_checkout_records.items` before the Stripe call (see the ADR addendum's point 6 for why the authoritative itemization lives there rather than in Stripe's own metadata). */
export interface CartCheckoutLineItem {
  productId: string;
  quantity: number;
  /** Cents. */
  unitAmount: number;
  currency: string;
  title: string;
  fulfillmentType: "physical" | "digital_or_service";
}

export interface CreatedCartCheckoutRecord {
  id: string;
}

export interface CartCheckoutRecordStore {
  create(input: {
    id: string;
    siteId: string;
    stripeSessionId: string;
    items: CartCheckoutLineItem[];
    currency: string;
    /** Cents — sum of every line's unitAmount * quantity, excluding shipping. */
    amountSubtotal: number;
    requiresShipping: boolean;
  }): Promise<CreatedCartCheckoutRecord>;
}

export interface CreateCartCheckoutDeps {
  products: CartProductStore;
  /** Reused unchanged from the one-off payment port (top of this file) — a connected Stripe account is the same account regardless of what's being charged. */
  stripeConnections: StripeConnectionStore;
  cartCheckoutRecords: CartCheckoutRecordStore;
  tenantStripe: TenantCartCheckoutProvider;
  shipping: CartShippingConfig;
}

export interface CreateCartCheckoutItemInput {
  productId: string;
  quantity: number;
}

export interface CreateCartCheckoutInput {
  /** Pre-generated by the caller — same reasoning as CreatePaymentCheckoutInput.id's own comment; also what apps/api's real adapter threads through Checkout's `client_reference_id`/`metadata` so a future webhook can resolve tenant context. */
  id: string;
  siteId: string;
  items: CreateCartCheckoutItemInput[];
  /** Derived server-side from the request's own Referer/Origin header by the caller (apps/api's route) — deliberately NOT accepted as a field a visitor's own request body sets; see the ADR addendum's point 5 for why (an open-redirect surface, the same reasoning every existing runtime checkout route here already avoids). */
  successUrl: string;
  cancelUrl: string;
}

export type CartCheckoutIssueReason = "not_found" | "invalid_quantity" | "out_of_stock";

export interface CartCheckoutIssue {
  productId: string;
  reason: CartCheckoutIssueReason;
}

export type CreateCartCheckoutOutcome =
  | { status: "created"; url: string }
  | { status: "empty_cart" }
  | { status: "invalid_items"; issues: CartCheckoutIssue[] }
  | { status: "mixed_currency" }
  | { status: "no_connection" }
  | { status: "provider_error" };

const MAX_CART_ITEM_QUANTITY = 999;

/**
 * The runtime API's cart-checkout mutation. Every item's price/currency/
 * title/fulfillmentType/stock is resolved from the CURRENT `products` row,
 * never from the visitor's own cart (which only ever supplies
 * `{productId, quantity}` pairs) — see this section's own module comment.
 * "Reject wholesale, name every problem" (the same discipline
 * `validateProductDocument` already documents): if ANY line fails
 * validation, the entire checkout is rejected with every issue named,
 * never a partial cart silently checked out with the bad lines dropped —
 * dropping lines would mean charging a different cart than the one the
 * visitor actually saw.
 */
export async function createCartCheckout(input: CreateCartCheckoutInput, deps: CreateCartCheckoutDeps): Promise<CreateCartCheckoutOutcome> {
  if (input.items.length === 0) return { status: "empty_cart" };

  // Duplicate productId entries are merged (quantities summed) rather than
  // rejected or turned into two Stripe line items for the same product —
  // see the ADR addendum's point 3.
  const mergedQuantities = new Map<string, number>();
  const order: string[] = [];
  for (const item of input.items) {
    if (!mergedQuantities.has(item.productId)) order.push(item.productId);
    mergedQuantities.set(item.productId, (mergedQuantities.get(item.productId) ?? 0) + item.quantity);
  }

  const issues: CartCheckoutIssue[] = [];
  const validated: CartCheckoutLineItem[] = [];

  for (const productId of order) {
    const quantity = mergedQuantities.get(productId)!;
    if (!Number.isInteger(quantity) || quantity <= 0 || quantity > MAX_CART_ITEM_QUANTITY) {
      issues.push({ productId, reason: "invalid_quantity" });
      continue;
    }

    const product = await deps.products.getProduct(productId);
    // A product that doesn't exist, isn't published (products_public_read
    // hides it), or belongs to a different site (that policy has no site
    // scoping of its own — there's no tenant context to scope against) all
    // read the same way from here: not something THIS site's cart can
    // check out. Never distinguished in the response — surfacing "this
    // product exists, just not on your site" would leak cross-tenant
    // existence information for no benefit to a legitimate caller.
    if (!product || product.siteId !== input.siteId) {
      issues.push({ productId, reason: "not_found" });
      continue;
    }

    if (product.fulfillmentType === "physical" && (product.stockCount ?? 0) < quantity) {
      issues.push({ productId, reason: "out_of_stock" });
      continue;
    }

    validated.push({
      productId,
      quantity,
      unitAmount: product.price,
      currency: product.currency,
      title: product.title,
      fulfillmentType: product.fulfillmentType,
    });
  }

  if (issues.length > 0) return { status: "invalid_items", issues };

  const currencies = new Set(validated.map((item) => item.currency));
  if (currencies.size > 1) return { status: "mixed_currency" };
  const currency = validated[0]!.currency;

  const connection = await deps.stripeConnections.getConnection(input.siteId);
  if (!connection) return { status: "no_connection" };

  const requiresShipping = validated.some((item) => item.fulfillmentType === "physical");
  const amountSubtotal = validated.reduce((sum, item) => sum + item.unitAmount * item.quantity, 0);

  let session: TenantCheckoutSession;
  try {
    session = await deps.tenantStripe.createCartCheckoutSession({
      accessToken: connection.accessToken,
      stripeAccountId: connection.stripeAccountId,
      items: validated.map((item) => ({ unitAmount: item.unitAmount, currency: item.currency, title: item.title, quantity: item.quantity })),
      currency,
      successUrl: input.successUrl,
      cancelUrl: input.cancelUrl,
      cartCheckoutRecordId: input.id,
      siteId: input.siteId,
      requiresShipping,
      shipping: deps.shipping,
    });
  } catch {
    return { status: "provider_error" };
  }

  await deps.cartCheckoutRecords.create({
    id: input.id,
    siteId: input.siteId,
    stripeSessionId: session.sessionId,
    items: validated,
    currency,
    amountSubtotal,
    requiresShipping,
  });

  return { status: "created", url: session.url };
}
