/**
 * KAN-1137 / ADR-0005: one-off payment blocks, bring-your-own Stripe.
 * Deliberately independent of @prefab/schema, @prefab/db and every
 * control-plane package (ADR-0010 / CLAUDE.md invariant 4) — apps/self-host
 * reimplements the storage/provider interfaces below against SQLite and a
 * fake-or-real TenantStripeProvider of its own, exactly the same "narrow
 * port, injected" shape submit.ts (FormManifestStore/SubmissionStore) and
 * book.ts (BookingStore/CalendarSyncPort) already use.
 */

/** The publish-safe manifest a Payment block's props are snapshotted into — see @prefab/db's `payment_blocks` table (0009_slice10_payments.sql). */
export interface PaymentBlockManifest {
  id: string;
  siteId: string;
  heading: string;
  description: string;
  buttonLabel: string;
  /** Cents — the one field a visitor's own request must never be able to override (a tampered request could otherwise pay whatever it likes). Always resolved from this manifest, never from the runtime checkout request body. */
  amount: number;
  currency: string;
  successMessage: string;
}

export interface PaymentBlockStore {
  getBlock(blockId: string): Promise<PaymentBlockManifest | null>;
}

export type StripeConnectionStatus = "connected" | "error";

/** What the runtime needs from a site's own connected Stripe account — apps/api's real shape (with the row's id/timestamps) lives in @prefab/db's stripe-connections.ts; only this much crosses the containment boundary. */
export interface StripeConnectionRecord {
  stripeAccountId: string;
  accessToken: string;
  status: StripeConnectionStatus;
}

export interface StripeConnectionStore {
  getConnection(siteId: string): Promise<StripeConnectionRecord | null>;
}

export interface CreatedPaymentRecord {
  id: string;
}

export interface PaymentRecordStore {
  create(input: { id: string; siteId: string; blockId: string; stripeSessionId: string; amount: number; currency: string }): Promise<CreatedPaymentRecord>;
}

export interface TenantCheckoutSession {
  sessionId: string;
  url: string;
}

/**
 * The narrow port this module needs from a tenant's own Stripe — mirrors
 * apps/api/src/lib/tenant-stripe-provider.ts's `TenantStripeProvider`
 * shape exactly, but only the one method (and only the fields)
 * `createPaymentCheckout` actually calls; `connect`/`constructEvent` are
 * apps/api-only concerns (OAuth and webhook verification are both
 * control-plane operations with no reason to cross into @prefab/runtime).
 */
export interface TenantCheckoutProvider {
  createCheckoutSession(input: {
    accessToken: string;
    stripeAccountId: string;
    amount: number;
    currency: string;
    productName: string;
    successUrl: string;
    cancelUrl: string;
    paymentRecordId: string;
    siteId: string;
  }): Promise<TenantCheckoutSession>;
}

export interface CreatePaymentCheckoutDeps {
  paymentBlocks: PaymentBlockStore;
  stripeConnections: StripeConnectionStore;
  paymentRecords: PaymentRecordStore;
  tenantStripe: TenantCheckoutProvider;
}

export interface CreatePaymentCheckoutInput {
  /** Pre-generated by the caller (mirrors submitForm's/createBooking's own `id`) — also what the real Stripe adapter threads through Checkout's `client_reference_id`/`metadata` so a real webhook (which has no siteId in its own URL) can resolve tenant context before ever touching `payment_records` (R20 / RLS). */
  id: string;
  blockId: string;
  successUrl: string;
  cancelUrl: string;
}

export type CreatePaymentCheckoutOutcome =
  | { status: "created"; url: string }
  | { status: "not_found" }
  | { status: "no_connection" }
  | { status: "provider_error" };

/**
 * The runtime API's payment-checkout mutation (ADR-0007's "form submit,
 * booking create, later checkout" — this is that "later"). The block's own
 * amount/currency are looked up from the publish-safe manifest, never
 * accepted from the caller, so a tampered request can never pay a
 * different amount than the block's own author configured. Provider
 * failures (no live Stripe account reachable, a bad/rotated tenant token)
 * surface as `provider_error` rather than a stored, doomed-to-never-
 * complete payment record — unlike submitForm/createBooking, there is no
 * "the write already happened, only notification can still fail" step
 * here: creating the Checkout session IS the operation that can fail, and
 * it happens before any row is written.
 */
export async function createPaymentCheckout(input: CreatePaymentCheckoutInput, deps: CreatePaymentCheckoutDeps): Promise<CreatePaymentCheckoutOutcome> {
  const block = await deps.paymentBlocks.getBlock(input.blockId);
  if (!block) return { status: "not_found" };

  const connection = await deps.stripeConnections.getConnection(block.siteId);
  if (!connection) return { status: "no_connection" };

  let session: TenantCheckoutSession;
  try {
    session = await deps.tenantStripe.createCheckoutSession({
      accessToken: connection.accessToken,
      stripeAccountId: connection.stripeAccountId,
      amount: block.amount,
      currency: block.currency,
      productName: block.heading || "Payment",
      successUrl: input.successUrl,
      cancelUrl: input.cancelUrl,
      paymentRecordId: input.id,
      siteId: block.siteId,
    });
  } catch {
    return { status: "provider_error" };
  }

  await deps.paymentRecords.create({
    id: input.id,
    siteId: block.siteId,
    blockId: block.id,
    stripeSessionId: session.sessionId,
    amount: block.amount,
    currency: block.currency,
  });

  return { status: "created", url: session.url };
}
