import { validateSubmissionValues } from "./validate.js";
import type { FieldValidationIssue } from "./types.js";
import type { RateLimiter } from "./rate-limit.js";
import type {
  EventSignupNotifier,
  EventSignupStore,
  EventSignupWidgetManifest,
  EventSignupWidgetStore,
} from "./event-signup-types.js";

export interface EventSignupDeps {
  widgets: EventSignupWidgetStore;
  signups: EventSignupStore;
  rateLimiter: RateLimiter;
  notifier: EventSignupNotifier;
}

export interface SignUpForEventInput {
  /** Pre-generated by the caller — @prefab/runtime never picks an id scheme (mirrors submitForm's own `id`). */
  id: string;
  widgetId: string;
  values: Record<string, unknown>;
  ip: string | null;
  /** Resolved by the caller from the site's own account, or null when there's none to notify — mirrors createBooking's own `ownerEmail` input exactly. */
  ownerEmail: string | null;
}

export type SignUpForEventOutcome =
  | { status: "confirmed"; signupId: string }
  | { status: "waitlisted"; signupId: string; position: number }
  | { status: "full" }
  | { status: "not_found" }
  | { status: "rate_limited"; retryAfterMs: number }
  | { status: "invalid"; issues: FieldValidationIssue[] };

/**
 * The runtime API's event sign-up mutation (KAN-1138, mirrors submitForm
 * exactly). Order matters, same as submitForm: rate-limiting gates the
 * request before a sign-up is ever attempted, then field validation, then
 * the store write itself — where confirmed-vs-waitlisted-vs-full is decided
 * atomically under the widget's own row lock (@prefab/db's
 * createEventSignup) rather than here. Notification is a best-effort step
 * layered on afterward and can never turn a stored sign-up back into a
 * failure.
 */
export async function signUpForEvent(input: SignUpForEventInput, deps: EventSignupDeps): Promise<SignUpForEventOutcome> {
  const widget = await deps.widgets.getWidget(input.widgetId);
  if (!widget) return { status: "not_found" };

  const siteLimit = deps.rateLimiter.consume(`site:${widget.siteId}`);
  if (!siteLimit.allowed) return { status: "rate_limited", retryAfterMs: siteLimit.retryAfterMs ?? 0 };
  const ipLimit = deps.rateLimiter.consume(`ip:${widget.siteId}:${input.ip ?? "unknown"}`);
  if (!ipLimit.allowed) return { status: "rate_limited", retryAfterMs: ipLimit.retryAfterMs ?? 0 };

  const validated = validateSubmissionValues(widget.fields, input.values);
  if (!validated.ok) return { status: "invalid", issues: validated.issues };

  const result = await deps.signups.create({
    id: input.id,
    widgetId: widget.id,
    siteId: widget.siteId,
    values: validated.values,
    capacity: widget.capacity,
    waitlistEnabled: widget.waitlistEnabled,
  });

  if (result.status === "full") return { status: "full" };

  await notifyBestEffort(deps, widget, result, input.ownerEmail);

  if (result.status === "confirmed") return { status: "confirmed", signupId: result.signup.id };
  return { status: "waitlisted", signupId: result.signup.id, position: result.position };
}

async function notifyBestEffort(
  deps: EventSignupDeps,
  widget: EventSignupWidgetManifest,
  result: Extract<Awaited<ReturnType<EventSignupStore["create"]>>, { status: "confirmed" | "waitlisted" }>,
  ownerEmail: string | null,
): Promise<void> {
  if (!ownerEmail) return;
  try {
    await deps.notifier.notify({ siteId: widget.siteId, widgetId: widget.id, signup: result.signup, ownerEmail });
  } catch {
    // Best-effort, same discipline as submitForm's notifyBestEffort and
    // book.ts's own notify path — the sign-up itself already succeeded.
  }
}
