import { validateSubmissionValues } from "./validate.js";
import type { FieldValidationIssue, FormManifest, SubmissionValues } from "./types.js";
import type { RateLimiter } from "./rate-limit.js";

export interface FormManifestStore {
  getForm(formId: string): Promise<FormManifest | null>;
}

export interface FormSettings {
  notifyEmail: string | null;
  webhookUrl: string | null;
  webhookSecret: string | null;
}

export interface FormSettingsStore {
  /** `siteId` is redundant with `formId` in principle, but threading it through is what lets a Postgres-backed implementation query `form_settings` — which carries no public read policy — inside the tenant context `submitForm` has already resolved, rather than needing a second, RLS-defeating lookup path of its own. */
  getSettings(formId: string, siteId: string): Promise<FormSettings | null>;
}

export interface CreatedSubmission {
  id: string;
  createdAt: string;
}

export interface SubmissionStore {
  create(input: { id: string; formId: string; siteId: string; values: SubmissionValues; ip: string | null }): Promise<CreatedSubmission>;
  setNotifyStatus(submissionId: string, siteId: string, status: "sent" | "failed", error: string | null): Promise<void>;
}

export interface TurnstileVerifier {
  verify(token: string, ip: string | null): Promise<{ success: boolean }>;
}

export interface FormNotifier {
  notify(input: { siteId: string; formId: string; submissionId: string; notifyEmail: string; values: SubmissionValues }): Promise<void>;
}

export interface WebhookQueue {
  enqueue(input: {
    siteId: string;
    formId: string;
    submissionId: string;
    url: string;
    webhookSecret: string | null;
    values: SubmissionValues;
    createdAt: string;
  }): Promise<void>;
}

export interface SubmitFormDeps {
  forms: FormManifestStore;
  formSettings: FormSettingsStore;
  submissions: SubmissionStore;
  rateLimiter: RateLimiter;
  turnstile: TurnstileVerifier;
  notifier: FormNotifier;
  webhooks: WebhookQueue;
}

export interface SubmitFormInput {
  /** Pre-generated by the caller — @prefab/runtime never picks an id scheme (Slice 7's self-host may not use ULIDs). */
  id: string;
  formId: string;
  values: Record<string, unknown>;
  ip: string | null;
  turnstileToken?: string;
}

export type SubmitFormOutcome =
  | { status: "created"; submissionId: string }
  | { status: "not_found" }
  | { status: "rate_limited"; retryAfterMs: number }
  | { status: "turnstile_failed" }
  | { status: "invalid"; issues: FieldValidationIssue[] };

/**
 * The runtime API's one real mutation (ADR-0007's "form submit, booking
 * create, later checkout"). Every dependency is injected as a narrow
 * interface — apps/api supplies Postgres-backed implementations today;
 * Slice 7's self-host runtime supplies SQLite-backed ones against this
 * exact same function, unchanged.
 *
 * Order matters: rate-limit and Turnstile gate the request before a
 * submission is ever created, but once those pass and validation succeeds,
 * the submission write itself is unconditional (R7.4) — notification and
 * webhook dispatch are best-effort steps layered on afterward and can
 * never turn a stored submission back into a failure.
 */
export async function submitForm(input: SubmitFormInput, deps: SubmitFormDeps): Promise<SubmitFormOutcome> {
  const form = await deps.forms.getForm(input.formId);
  if (!form) return { status: "not_found" };

  const siteLimit = deps.rateLimiter.consume(`site:${form.siteId}`);
  if (!siteLimit.allowed) return { status: "rate_limited", retryAfterMs: siteLimit.retryAfterMs ?? 0 };
  const ipLimit = deps.rateLimiter.consume(`ip:${form.siteId}:${input.ip ?? "unknown"}`);
  if (!ipLimit.allowed) return { status: "rate_limited", retryAfterMs: ipLimit.retryAfterMs ?? 0 };

  if (form.turnstileEnabled) {
    if (!input.turnstileToken) return { status: "turnstile_failed" };
    const verified = await deps.turnstile.verify(input.turnstileToken, input.ip);
    if (!verified.success) return { status: "turnstile_failed" };
  }

  const validated = validateSubmissionValues(form.fields, input.values);
  if (!validated.ok) return { status: "invalid", issues: validated.issues };

  const created = await deps.submissions.create({
    id: input.id,
    formId: form.id,
    siteId: form.siteId,
    values: validated.values,
    ip: input.ip,
  });

  const settings = await deps.formSettings.getSettings(form.id, form.siteId);
  await notifyBestEffort(deps, form, settings, created, validated.values);
  await webhookBestEffort(deps, form, settings, created, validated.values);

  return { status: "created", submissionId: created.id };
}

async function notifyBestEffort(
  deps: SubmitFormDeps,
  form: FormManifest,
  settings: FormSettings | null,
  created: CreatedSubmission,
  values: SubmissionValues,
): Promise<void> {
  if (!settings?.notifyEmail) return;

  try {
    await deps.notifier.notify({ siteId: form.siteId, formId: form.id, submissionId: created.id, notifyEmail: settings.notifyEmail, values });
    await deps.submissions.setNotifyStatus(created.id, form.siteId, "sent", null);
  } catch (error) {
    // R7.4: the submission is already stored — a notification failure
    // (provider down, bad credentials) surfaces as a status on the record,
    // never as a lost or errored request.
    await deps.submissions.setNotifyStatus(created.id, form.siteId, "failed", error instanceof Error ? error.message : String(error));
  }
}

async function webhookBestEffort(
  deps: SubmitFormDeps,
  form: FormManifest,
  settings: FormSettings | null,
  created: CreatedSubmission,
  values: SubmissionValues,
): Promise<void> {
  if (!settings?.webhookUrl) return;
  await deps.webhooks.enqueue({
    siteId: form.siteId,
    formId: form.id,
    submissionId: created.id,
    url: settings.webhookUrl,
    webhookSecret: settings.webhookSecret,
    values,
    createdAt: created.createdAt,
  });
}
