import { cp, mkdir, writeFile } from "node:fs/promises";
import path from "node:path";
import { fileURLToPath } from "node:url";
import {
  BREAKPOINTS,
  BREAKPOINT_MIN_WIDTH,
  DEFAULT_THEME_TOKENS,
  type PageDocument,
  type PostDocument,
  type SiteManifest,
  type ThemeDocument,
} from "@prefab/schema";
import { SITE_PAGE_ASTRO } from "./page-template.js";

const PACKAGE_ROOT = path.join(path.dirname(fileURLToPath(import.meta.url)), "..");
/** @prefab/blocks is a sibling workspace package — see this file's module comment for why its source is copied wholesale rather than depended on. */
const BLOCKS_SRC_ROOT = path.join(PACKAGE_ROOT, "..", "blocks", "src");

// Pinned to exactly what packages/publish's own hosted pipeline builds
// against (see this package's package.json) — R9's pixel-fidelity claim
// requires the ejected project to render with the identical Astro/React
// versions, not just the identical component source.
const ASTRO_VERSION = "7.2.8";
const ASTROJS_REACT_VERSION = "6.0.4";
const REACT_VERSION = "19.0.0";
const ZOD_VERSION = "4.4.3";

export interface EjectSiteInput {
  site: SiteManifest;
  theme: ThemeDocument;
  pages: PageDocument[];
  posts?: PostDocument[];
  runtimeApiUrl?: string;
  turnstileSiteKey?: string;
  outDir: string;
}

export interface EjectResult {
  outDir: string;
}

function prefabSchemaShimSource(): string {
  return `// Generated by \`prefab eject\` (Slice 7, ADR-0010 tier c) — do not import
// this from anything other than the alias below. It vendors the tiny
// handful of @prefab/schema exports @prefab/blocks' components actually
// touch at runtime; everything else a block imports from "@prefab/schema"
// is \`import type\`, erased entirely at build time, so it never needs a
// real module here at all. Aliased to the "@prefab/schema" bare specifier
// in astro.config.mjs, which is what lets every file under src/blocks be a
// byte-for-byte copy of this site's own block library — nothing to
// rewrite, nothing to risk diverging (R9's pixel-fidelity claim).
export const BREAKPOINTS = ${JSON.stringify(BREAKPOINTS)};
export const BREAKPOINT_MIN_WIDTH = ${JSON.stringify(BREAKPOINT_MIN_WIDTH)};

export function isUlid(value) {
  return typeof value === "string" && /^[0-9A-HJKMNP-TV-Z]{26}$/.test(value);
}

export const DEFAULT_THEME_TOKENS = ${JSON.stringify(DEFAULT_THEME_TOKENS, null, 2)};

// KAN-1204: @prefab/blocks' theme-css.ts now imports \`resolveThemeTokens\` as
// a runtime value from "@prefab/schema" (it used to be defined locally in
// that file) so packages/db can share the same merge logic at the DB-read
// boundary — see that function's own doc comment in the real
// @prefab/schema package. The copied theme-css.ts (src/blocks, byte-for-byte
// per this file's module comment) re-exports it, and \`[...slug].astro\`
// (this file's own SITE_PAGE_ASTRO) calls it directly, so this shim needs a
// real, working implementation, not just a type — the same reason
// DEFAULT_THEME_TOKENS above is a real value and not \`import type\`.
export function resolveThemeTokens(tokens, defaults = DEFAULT_THEME_TOKENS) {
  return {
    color: { ...defaults.color, ...tokens.color },
    fontSize: { ...defaults.fontSize, ...tokens.fontSize },
    spacing: { ...defaults.spacing, ...tokens.spacing },
    radius: { ...defaults.radius, ...tokens.radius },
    fontFamily: { ...defaults.fontFamily, ...tokens.fontFamily },
    lineHeight: { ...defaults.lineHeight, ...tokens.lineHeight },
  };
}

export class BlockRegistry {
  #definitions = new Map();
  register(definition) {
    this.#definitions.set(definition.type, definition);
    return this;
  }
  get(type) {
    return this.#definitions.get(type);
  }
  has(type) {
    return this.#definitions.has(type);
  }
  types() {
    return [...this.#definitions.keys()];
  }
}
`;
}

function prefabSchemaShimTypesSource(): string {
  return `// Type-only companion to index.mjs — never imported at runtime (Vite never
// resolves a "import type" specifier to actual module code), only read by
// an editor or a TypeScript compile for the types every block file's
// "import type" pulls in. Kept intentionally loose (Record<string, unknown>
// stand-ins) since
// no first-party block relies on any of these being narrower than that at
// eject time — the props themselves already came from a validated document.
export type OverridableBreakpoint = "md" | "lg";
export type Breakpoint = "base" | OverridableBreakpoint;

export interface ResponsiveOverride {
  hidden?: boolean;
  spacing?: "xs" | "sm" | "element" | "lg" | "section";
  columns?: number;
}
export interface BlockResponsive {
  md?: ResponsiveOverride;
  lg?: ResponsiveOverride;
}

// ADR-0014 (KAN-1129): the free-positioning geometry @prefab/blocks'
// free-position.tsx (vendored alongside every other block source, see this
// file's own \`cp\` of BLOCKS_SRC_ROOT) imports as \`import type\` from
// "@prefab/schema" — never a runtime value, so (like everything else in
// this file) it never needs a real implementation here, only a type shape
// for the ejected project's own type-checking to resolve against.
export interface FreeRect {
  x: number;
  y: number;
  w: number;
  h: number;
  rotate: number;
  opacity: number;
}
export interface FreePosition {
  base: FreeRect;
  md?: Partial<FreeRect>;
  lg?: Partial<FreeRect>;
}
export interface BlockNode {
  id: string;
  type: string;
  parent: string | null;
  order: number;
  schemaVersion: number;
  props: Record<string, unknown>;
  responsive?: BlockResponsive;
  position?: FreePosition;
  // ADR-0015 (KAN-1152): scroll-triggered reveal opt-in — see this file's
  // module comment above \`FreePosition\` for why a runtime-inert, type-only
  // field like this still needs a shim entry: the ejected project's own
  // type-check of the copied block sources (src/blocks, cp'd verbatim from
  // packages/blocks/src) resolves \`@prefab/schema\` to this shim.
  scrollReveal?: boolean;
}

export interface ThemeTokens {
  color: Record<string, string>;
  fontSize: Record<string, string>;
  spacing: Record<string, string>;
  radius: Record<string, string>;
  // KAN-1204: this shim had already fallen behind @prefab/schema's real
  // ThemeTokensSchema by one group (fontFamily, added earlier) before this
  // change added a second (lineHeight) — both added here now. The copied
  // block sources (src/blocks, cp'd verbatim below) reference
  // tokens.fontFamily/tokens.lineHeight (theme-css.ts's
  // themeTokensToStyleVars/resolveThemeTokens), so an ejected project's own
  // \`tsc\`/\`astro build\` needs both fields on this shim to type-check
  // against, the same reason \`scrollReveal\` was added to \`BlockNode\` below.
  fontFamily: Record<string, string>;
  lineHeight: Record<string, string>;
}

export interface PostDocument {
  id: string;
  siteId: string;
  slug: string;
  title: string;
  schemaVersion: number;
  version: number;
  date: string;
  author: string;
  tags: string[];
  cover: string | null;
  body: string;
  locale: string;
  status: "draft" | "published";
}

export interface BlockTypeDefinition<Props = Record<string, unknown>> {
  type: string;
  version: number;
  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  propsSchema: any;
  defaultProps: Props;
  migrations: Record<number, (props: Record<string, unknown>) => Record<string, unknown>>;
}
`;
}

function astroConfigSource(): string {
  return `import { defineConfig } from "astro/config";
import react from "@astrojs/react";
import path from "node:path";
import { fileURLToPath } from "node:url";

// Ejected by \`prefab eject\` (ADR-0010 tier c). Builds with plain
// \`npm install && npm run build\` against upstream Astro — no pre-fab
// package is a dependency of this project (R11).
const here = path.dirname(fileURLToPath(import.meta.url));

export default defineConfig({
  integrations: [react()],
  vite: {
    resolve: {
      alias: {
        "@prefab/schema": path.join(here, "src", "prefab-schema", "index.mjs"),
        "@prefab/blocks": path.join(here, "src", "blocks", "index.ts"),
      },
    },
  },
});
`;
}

function packageJsonSource(siteSlug: string): string {
  return `${JSON.stringify(
    {
      name: `${siteSlug}-site`,
      private: true,
      version: "0.0.0",
      type: "module",
      scripts: {
        dev: "astro dev",
        build: "astro build",
        preview: "astro preview",
      },
      dependencies: {
        astro: ASTRO_VERSION,
        "@astrojs/react": ASTROJS_REACT_VERSION,
        react: REACT_VERSION,
        "react-dom": REACT_VERSION,
        zod: ZOD_VERSION,
      },
    },
    null,
    2,
  )}\n`;
}

function tsconfigSource(): string {
  return `${JSON.stringify(
    {
      extends: "astro/tsconfigs/base",
      include: [".astro/types.d.ts", "**/*"],
      exclude: ["dist"],
    },
    null,
    2,
  )}\n`;
}

function readmeSource(siteSlug: string): string {
  return `# ${siteSlug} — ejected from pre-fab

A conventional Astro project (ADR-0010 tier c). No pre-fab package is
required at runtime (R11) — every block component is copied source, and
the handful of small \`@prefab/schema\` helpers it needs are vendored in
\`src/prefab-schema/\`.

## Build

\`\`\`
npm install
npm run build
\`\`\`

## Develop

\`\`\`
npm install
npm run dev
\`\`\`

## Forms

This export's Form block(s) post to the \`runtimeApiUrl\` baked into
\`src/data.json\` at eject time. That only keeps working if something
implements pre-fab's runtime API at that address — self-host it with
\`apps/self-host\` (ADR-0010 tier b), or remove/replace the Form block if you
don't need it.

This project receives no updates from pre-fab going forward — the same
"fork and freeze" relationship a template has with the site created from it
(ADR-0011). It's yours now.
`;
}

/** Newest-first, id as a stable tiebreaker — mirrors build-worker.ts's own sort so an ejected build routes/paginates posts identically to the hosted one. */
function sortPostsNewestFirst(posts: PostDocument[]): PostDocument[] {
  return [...posts].sort((a, b) => (a.date === b.date ? (a.id < b.id ? 1 : -1) : a.date < b.date ? 1 : -1));
}

/**
 * Export tier (c) (ADR-0010): generates a standalone Astro project from a
 * document tree. Reuses `SITE_PAGE_ASTRO` verbatim — the exact same page
 * template the hosted publish pipeline builds with (build-worker.ts) — so
 * fidelity (R9) is a property of sharing one template, not of two
 * templates being kept in sync by hand.
 */
export async function ejectSite(input: EjectSiteInput): Promise<EjectResult> {
  const { outDir } = input;
  await mkdir(outDir, { recursive: true });

  await cp(BLOCKS_SRC_ROOT, path.join(outDir, "src", "blocks"), { recursive: true });

  const schemaShimDir = path.join(outDir, "src", "prefab-schema");
  await mkdir(schemaShimDir, { recursive: true });
  await writeFile(path.join(schemaShimDir, "index.mjs"), prefabSchemaShimSource(), "utf8");
  await writeFile(path.join(schemaShimDir, "index.d.ts"), prefabSchemaShimTypesSource(), "utf8");

  const pagesDir = path.join(outDir, "src", "pages");
  await mkdir(pagesDir, { recursive: true });
  await writeFile(path.join(pagesDir, "[...slug].astro"), SITE_PAGE_ASTRO, "utf8");

  const data = {
    site: input.site,
    theme: input.theme,
    pages: input.pages,
    posts: sortPostsNewestFirst(input.posts ?? []),
    runtimeApiUrl: input.runtimeApiUrl ?? "",
    turnstileSiteKey: input.turnstileSiteKey ?? "",
  };
  await writeFile(path.join(outDir, "src", "data.json"), JSON.stringify(data), "utf8");

  await writeFile(path.join(outDir, "astro.config.mjs"), astroConfigSource(), "utf8");
  await writeFile(path.join(outDir, "package.json"), packageJsonSource(input.site.slug), "utf8");
  await writeFile(path.join(outDir, "tsconfig.json"), tsconfigSource(), "utf8");
  await writeFile(path.join(outDir, "README.md"), readmeSource(input.site.slug), "utf8");
  await writeFile(path.join(outDir, ".gitignore"), "node_modules/\ndist/\n.astro/\n", "utf8");

  return { outDir };
}
